---
title: "Importing Fred Data"
output: html_notebook
---

```{r}
#remove objects in workspace
rm(list=ls()[! ls() %in% c("object1","object2")]) #remove all but the objects you define e.g. object1 and object2

#load required packages
library(RQuantLib)
library(quantstrat) 
library(quantmod)
library(PerformanceAnalytics)
```

```{r}
#Download FRED data for 10Yr US Bonds
start.date <- as.Date("1972-1-31")
end.date <- as.Date("2016-12-31")

getSymbols("DTB3", src="FRED") #download data


Tbill.yield <- to.monthly(DTB3,indexAt='lastof',drop.time=TRUE)[,4] #convert to monthly
Tbill.yield <- Tbill.yield[paste(start.date,end.date,sep="/")] #subset to required period

rm(start.date,end.date)
```

```{r}
#save as CSV files
write.zoo(Tbill.yield, file="FinalData/TBills.csv", sep=",")
```

```{r}
#Import saved US10YR csv file into new xts object - copy this into any other R files that need the research
rm(list = ls()) 

symbols <- c("SP500","EAFE","US10YR","GSCI","NAREIT")

getSymbols(symbols,
           src = "csv",
           dir="FinalData",
           #from=startDate,
           #to=endDate,
           col.names=c("Close")
           #auto.assign=TRUE,
           #index.class=c("POSIXt","POSIXct"),
           #adjust = TRUE
           )

rm(symbols)
```
